# API service configuration
spring:
  application:
    name: api-service

  profiles:
    active: dev

  redis:
    host: localhost
    port: 6379

server:
  port: 8080

flight:
  cache:
    local:
      max-size: 10000 # L1 Caffeine cache size
      ttl-minutes: 10 # L1 cache TTL
    remote:
      ttl-minutes: 30 # L2 Redis cache TTL

logging:
  level:
    root: INFO
    com.flighttracker: DEBUG
